<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto

namespace Google\Protobuf\Compiler\CodeGeneratorResponse;

/**
 * Sync with code_generator.h.
 *
 * Protobuf type <code>google.protobuf.compiler.CodeGeneratorResponse.Feature</code>
 */
class Feature
{
    /**
     * Generated from protobuf enum <code>FEATURE_NONE = 0;</code>
     */
    const FEATURE_NONE = 0;
    /**
     * Generated from protobuf enum <code>FEATURE_PROTO3_OPTIONAL = 1;</code>
     */
    const FEATURE_PROTO3_OPTIONAL = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Feature::class, \Google\Protobuf\Compiler\CodeGeneratorResponse_Feature::class);

